### ISSUE TITLE
牛老婆会卡住，原因不明

### ISSUE THREAD

**Issue by keqingyyds** [Rinco304/AnimeWife#5]
莫名其妙就一直显示有人在交换 然后卡死。

**Comment by Rinco304** [comment]
交换老婆时进行牛老婆无法复现此情况，请问当时是怎么触发的？如果是稳定触发的话可以提供一个触发方式

**Comment by keqingyyds** [comment]
不知道，只知道是交换老婆的时候一直提示双方有人在进行换妻。  无论是谁操作都是这样
