### ISSUE TITLE
您的老婆库很好用，已经过去半年了，好兄弟有没有考虑更新老婆库😍

### ISSUE THREAD

**Issue by shadlc** [Rinco304/AnimeWife#6]

**Comment by Rinco304** [comment]
这个月有点忙😭有空的时候我大量更新一下吧（有群管理员添加老婆的功能，也可以呼吁群友帮忙维护一下）

**Comment by shadlc** [comment]
> 这个月有点忙😭有空的时候我大量更新一下吧（有群管理员添加老婆的功能，也可以呼吁群友帮忙维护一下）

好耶！赛高！

**Comment by Rinco304** [comment]
> 好耶！赛高！

更新了一批新老婆在 Releases与网盘分享中的 `wife2.rar` ，下载后添加到资源文件夹中即可，新老婆主要以新番为主，使用愉快~

**Comment by shadlc** [comment]
> > 好耶！赛高！
> 
> 更新了一批新老婆在 Releases与网盘分享中的 `wife2.rar` ，下载后添加到资源文件夹中即可，新老婆主要以新番为主，使用愉快~

很吼很吼，非常刑
