### ISSUE TITLE
指令触发报错

### ISSUE THREAD

**Issue by Zijun9297** [Rinco304/AnimeWife#7]
作者您好，我在使用此插件的时候偶尔会遇到触发不了指令的情况，报错如下图，表现为某个人当天之内都会在触发抽老婆的指令时报错，希望能够解决
![image](https://github.com/user-attachments/assets/38926c9b-0646-4b75-a8a6-e860e627d57a)

**Comment by Zijun9297** [comment]
忘了说明补充一下，协议端是napcat

**Comment by Rinco304** [comment]
从提供的日志看起来可能是 napcat 的问题（代码报错在发送消息的地方，说明是执行了功能代码的，但是发送消息时遇到了Timeout错误）
我在napcat的issue中找到了类似的问题（ NapNeko/NapCatQQ#223 、NapNeko/NapCatQQ#262 ）
我没有使用napcat作为协议端，暂时不能复现测试你描述的情况，你可以尝试 **重新登陆** 或者 **更新QQ** 或者 **更新napcat** 版本试试能不能解决问题，也可以仔细翻看napcat的issue看看还有没有相似情况的，如果还是不能解决问题可以在napcat那里开一个issue，我也弄一个napcat协议端帮忙测试

**Comment by MliKiowa** [comment]
这是进tx的消息屏蔽了

**Comment by Zijun9297** [comment]
非常感谢插两位作者的用心解答，很有帮助，已经明白问题的原因了
